# Generated by Django 4.2.23 on 2025-08-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('nome_full', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razão Social')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agencia_conta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Agência/Conta')),
                ('pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pix')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/logo/')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('template_proposta', models.FileField(blank=True, help_text='Template .docx específico para essa empresa.', null=True, upload_to='templates_propostas_empresas/')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, null=True, verbose_name='Nome Completo')),
                ('departamento', models.CharField(max_length=100, null=True, verbose_name='Departamento')),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('megaapi_instance_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave de Instância MegaAPI')),
                ('megaapi_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token MegaAPI')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='perfil.empresa', verbose_name='Empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Envio')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha do Email')),
                ('servidor_imap', models.CharField(max_length=255, null=True, verbose_name='Servidor IMAP')),
                ('porta_imap', models.IntegerField(default=993, null=True, verbose_name='Porta IMAP')),
                ('pasta_imap', models.CharField(default='INBOX', max_length=50, null=True, verbose_name='Pasta IMAP')),
                ('usar_ssl_imap', models.BooleanField(default=True, null=True, verbose_name='Usar SSL IMAP')),
                ('servidor_smtp', models.CharField(max_length=255, null=True, verbose_name='Servidor SMTP')),
                ('porta_smtp', models.IntegerField(default=587, null=True, verbose_name='Porta SMTP')),
                ('usar_tls_smtp', models.BooleanField(default=True, null=True, verbose_name='Usar TLS SMTP')),
                ('email_resposta', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Resposta')),
                ('limite_diario', models.IntegerField(default=100, null=True, verbose_name='Limite de Envios Diários')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Email',
                'verbose_name_plural': 'Configurações de Email',
            },
        ),
    ]
