# Generated by Django 5.2.4 on 2025-07-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_empresa_perfil_empresa'),
    ]

    operations = [
        # Todas as operações AlterField foram comentadas porque os campos
        # não existem mais no arquivo models.py.

        # migrations.AlterField(
        #     model_name='perfil',
        #     name='bairro',
        #     field=models.CharField(max_length=30, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='cep',
        #     field=models.CharField(max_length=8, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='cidade',
        #     field=models.CharField(max_length=30, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='complemento',
        #     field=models.CharField(max_length=30, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='cpf',
        #     field=models.CharField(max_length=11, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='data_nascimento',
        #     field=models.DateField(null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='endereco',
        #     field=models.CharField(max_length=50, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='estado',
        #     field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='idade',
        #     field=models.PositiveIntegerField(null=True),
        # ),
        # migrations.AlterField(
        #     model_name='perfil',
        #     name='numero',
        #     field=models.CharField(max_length=5, null=True),
        # ),
    ]
