# Generated by Django 5.2.4 on 2025-07-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_perfil_bairro_alter_perfil_cep_and_more'),
    ]

    operations = [
        # Todas as operações foram comentadas porque os campos já foram removidos do models.py
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='bairro',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='cep',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='cidade',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='complemento',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='cpf',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='data_nascimento',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='endereco',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='estado',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='idade',
        # ),
        # migrations.RemoveField(
        #     model_name='perfil',
        #     name='numero',
        # ),
    ]
