# Generated by Django 3.2.25 on 2025-07-22 16:30

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_remove_perfil_bairro_remove_perfil_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('servidor_imap', models.CharField(max_length=100)),
                ('pasta', models.CharField(default='INBOX', max_length=50)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_email', to='perfil.empresa')),
            ],
        ),
    ]
