# Generated by Django 3.2.25 on 2025-07-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_configuracaoemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='porta_smtp',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='servidor_smtp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/logo/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_full',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.empresa'),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='servidor_imap',
            field=models.CharField(max_length=255),
        ),
    ]
