# Generated by Django 3.2.25 on 2025-07-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_auto_20250726_1906'),
    ]

    operations = [
    ]
