# Generated by Django 3.2.25 on 2025-07-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_fix_migration_order'),
    ]

    operations = [
    ]
