# Generated by Django 3.2.25 on 2025-07-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_fix_migration_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoemail',
            options={'verbose_name': 'Configuração de Email', 'verbose_name_plural': 'Configurações de Email'},
        ),
        migrations.RemoveField(
            model_name='configuracaoemail',
            name='pasta',
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='email_resposta',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Resposta'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='limite_diario',
            field=models.IntegerField(default=100, null=True, verbose_name='Limite de Envios Diários'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='pasta_imap',
            field=models.CharField(default='INBOX', max_length=50, null=True, verbose_name='Pasta IMAP'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='porta_imap',
            field=models.IntegerField(default=993, null=True, verbose_name='Porta IMAP'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='usar_ssl_imap',
            field=models.BooleanField(default=True, null=True, verbose_name='Usar SSL IMAP'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='usar_tls_smtp',
            field=models.BooleanField(default=True, null=True, verbose_name='Usar TLS SMTP'),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email de Envio'),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='porta_smtp',
            field=models.IntegerField(default=587, null=True, verbose_name='Porta SMTP'),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='senha',
            field=models.CharField(max_length=255, verbose_name='Senha do Email'),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='servidor_imap',
            field=models.CharField(max_length=255, null=True, verbose_name='Servidor IMAP'),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='servidor_smtp',
            field=models.CharField(max_length=255, null=True, verbose_name='Servidor SMTP'),
        ),
    ]
