# Generated by Django 3.2.25 on 2025-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_auto_20250726_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.CharField(max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
