# Generated by Django 3.2.25 on 2025-07-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_auto_20250728_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='template_proposta',
            field=models.FileField(blank=True, help_text='Template .docx específico para essa empresa.', null=True, upload_to='templates_propostas_empresas/'),
        ),
    ]
