# Generated by Django 3.2.25 on 2025-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_empresa_template_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='zapi_instance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Instância Z-API'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='zapi_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Z-API'),
        ),
    ]
