# Generated by Django 3.2.25 on 2025-07-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_auto_20250729_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='zapi_security_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de Segurança da Conta'),
        ),
    ]
