# Generated by Django 3.2.25 on 2025-07-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0016_empresa_zapi_security_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='zapi_instance',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='zapi_security_token',
            new_name='security_token',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='zapi_token',
            new_name='token',
        ),
    ]
