# Generated by Django 3.2.25 on 2025-07-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0017_auto_20250729_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='security_token',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='token',
        ),
        migrations.AddField(
            model_name='empresa',
            name='megaapi_instance_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='megaapi_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
