# Generated by Django 3.2.25 on 2025-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0018_auto_20250729_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='megaapi_instance_key',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='megaapi_token',
        ),
        migrations.AddField(
            model_name='perfil',
            name='megaapi_instance_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave de Instância MegaAPI'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='megaapi_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token MegaAPI'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_comercial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Comercial WhatsApp'),
        ),
    ]
