# Generated by Django 3.2.25 on 2025-07-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_auto_20250729_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='numero_comercial',
        ),
    ]
