# Generated by Django 3.2.25 on 2025-07-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0020_remove_perfil_numero_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='agencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pix'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razão Social'),
        ),
    ]
