# Generated by Django 3.2.25 on 2025-07-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0021_auto_20250731_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='agencia',
            new_name='agencia_conta',
        ),
    ]
