# Generated by Django 3.2.25 on 2025-07-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0022_rename_agencia_empresa_agencia_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='agencia_conta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agência/Conta'),
        ),
    ]
