# Generated by Django 3.2.25 on 2025-08-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0023_alter_empresa_agencia_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
