# Generated by Django 4.2.23 on 2025-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0024_empresa_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usa_ia_precificacao',
            field=models.BooleanField(default=False, help_text='Marque esta opção para permitir que usuários desta empresa usem a sugestão de preço da IA.', verbose_name='Usa IA para Precificação?'),
        ),
    ]
