# Generated by Django 4.2.23 on 2025-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0025_empresa_usa_ia_precificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dias_expiracao_dados',
            field=models.IntegerField(blank=True, help_text='CUIDADO: Após este período, os dados da cotação serão permanentemente apagados. Deixe em branco para nunca apagar.', null=True, verbose_name='Tempo para Apagar Cotações (dias)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dias_expiracao_visualizacao',
            field=models.IntegerField(blank=True, help_text='Após este período, as cotações não aparecerão nas listas e buscas. Deixe em branco para nunca ocultar.', null=True, verbose_name='Tempo para Ocultar Cotações (dias)'),
        ),
    ]
