# Generated by Django 4.2.23 on 2025-09-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0026_empresa_dias_expiracao_dados_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('pode_ver_dashboard', 'Pode ver o dashboard analítico')]},
        ),
    ]
