# Generated by Django 4.2.23 on 2025-09-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0027_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome_full',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
