# Generated by Django 4.2.23 on 2025-10-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0028_alter_empresa_nome_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID do Cliente (Asaas)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='asaas_ultima_cobranca_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Última Cobrança PIX (Asaas)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status_assinatura',
            field=models.CharField(choices=[('TESTE', 'Período de Teste'), ('ATIVA', 'Ativa'), ('PENDENTE', 'Pagamento Pendente'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='TESTE', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Mensalidade (R$)'),
        ),
    ]
