# Generated by Django 4.2.23 on 2025-10-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0029_empresa_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
