# Generated by Django 4.2.23 on 2025-10-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0030_empresa_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='proxy_url',
            field=models.CharField(blank=True, help_text='Formato: http://usuario:senha@host:porta', max_length=255, null=True, verbose_name='URL do Proxy'),
        ),
    ]
