# Generated by Django 4.2.23 on 2025-10-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0031_perfil_proxy_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='megaapi_instance_key',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='megaapi_token',
        ),
        migrations.AddField(
            model_name='perfil',
            name='api_credentials',
            field=models.JSONField(blank=True, default=dict, help_text='MegaAPI: {"instance_key": "...", "token": "..."} | API Própria: {"instance_name": "...", "port": "..."}', null=True, verbose_name='Credenciais da API'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='api_provider',
            field=models.CharField(choices=[('MEGAAPI', 'Mega API'), ('SELF_HOSTED', 'API Própria (Preciflow)')], default='MEGAAPI', max_length=20, verbose_name='Provedor da API de WhatsApp'),
        ),
    ]
