# Generated by Django 4.2.23 on 2025-11-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0032_remove_perfil_megaapi_instance_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='api_fiscal_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token da API Fiscal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_a1',
            field=models.FileField(blank=True, help_text='Arquivo .pfx ou .p12 do Certificado Digital A1', null=True, upload_to='certificados_a1/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_senha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha do Certificado'),
        ),
    ]
