# Generated by Django 4.2.23 on 2025-11-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0033_empresa_api_fiscal_token_empresa_certificado_a1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='api_fiscal_token',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='certificado_a1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='certificado_senha',
        ),
    ]
