# Generated by Django 4.2.23 on 2025-08-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('prazo_coleta', models.CharField(max_length=50)),
                ('prazo_entrega', models.CharField(max_length=50)),
                ('tipo_frete', models.CharField(choices=[('Transporte de Cargas', 'Transporte de Cargas'), ('Mudanças', 'Mudanças'), ('Material Sem Nota', 'Material Sem Nota'), ('Moto', 'Moto'), ('Carga em Geral', 'Carga em Geral'), ('Máquina', 'Máquina'), ('Veículos', 'Veículos'), ('Não especificado', 'Não especificado')], default='Transporte de Cargas', max_length=100)),
                ('rastreio', models.CharField(blank=True, choices=[('Cargas', 'Cargas'), ('CoteFrete', 'CoteFrete'), ('CoteTransporte', 'CoteTransporte'), ('Outros', 'Outros'), ('Email', 'Email'), ('Google', 'Google'), ('Guia', 'Guia'), ('Indicação', 'Indicação'), ('PortalDosFretes', 'PortalDosFretes'), ('Transcedental', 'Transcedental'), ('Transvias', 'Transvias'), ('Whats Existencial', 'Whats Existencial')], max_length=50)),
                ('status_cotacao', models.CharField(choices=[('Em Negociação', 'Em Negociação'), ('Aprovada', 'Aprovada'), ('Cancelada', 'Cancelada'), ('Reprovada', 'Reprovada')], default='Em Negociação', max_length=50)),
                ('status_envio', models.CharField(choices=[('Duplicada', 'Duplicada'), ('Rejeitada', 'Rejeitada'), ('Falta Cubagem', 'Falta Cubagem'), ('Falta Preço', 'Falta Preço'), ('Enviado Whats + Email', 'Enviado Whats + Email'), ('Enviado Whats', 'Enviado Whats'), ('Enviado Email', 'Enviado Email'), ('Envio Negado', 'Envio Negado'), ('Faltam Medidas', 'Faltam Medidas'), ('Não Enviado', 'Não Enviado'), ('Aguardando Coleta', 'Aguardando Coleta'), ('Aguardando Pagamento', 'Aguardando Pagamento')], default='Não Enviado', max_length=50)),
                ('volumes', models.IntegerField(blank=True, null=True)),
                ('cubagem', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_mercadoria', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_proposta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('proposta_gerada', models.FileField(blank=True, null=True, upload_to='propostas/')),
                ('email_message_id', models.CharField(blank=True, help_text='Message-ID do email para evitar duplicação', max_length=255, null=True, unique=True)),
                ('numero_sequencial_empresa', models.PositiveIntegerField(blank=True, editable=False, help_text='Número sequencial único por empresa, usado para gerar o número da proposta.', null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='perfil.empresa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('empresa', 'numero_sequencial_empresa')},
            },
        ),
        migrations.CreateModel(
            name='TemplateProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='templates_propostas/')),
                ('mensagem_padrao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='emails_anexos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_com_sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_enviados', to='quoteflow.cotacao')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
