# Generated by Django 3.2.25 on 2025-07-29 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quoteflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='emails_anexos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_com_sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_enviados', to='quoteflow.cotacao')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
