# Generated by Django 3.2.25 on 2025-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0002_emailenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='email_message_id',
            field=models.CharField(blank=True, help_text='Message-ID do email para evitar duplicação', max_length=255, null=True, unique=True),
        ),
    ]
