# Generated by Django 3.2.25 on 2025-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0003_cotacao_email_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='valor_proposta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
