# Generated by Django 3.2.25 on 2025-07-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0004_alter_cotacao_valor_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='cubagem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='tipo_frete',
            field=models.CharField(choices=[('Transporte de Cargas', 'Transporte de Cargas'), ('Mudanças', 'CoteFrMudançasete'), ('Material Sem Nota', 'Material Sem Nota'), ('Moto', 'Moto'), ('Carga em Geral', 'Carga em Geral'), ('Máquina', 'Máquina')], default='Transporte de Cargas', max_length=100),
        ),
    ]
