# Generated by Django 3.2.25 on 2025-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0005_auto_20250730_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='tipo_frete',
            field=models.CharField(choices=[('Transporte de Cargas', 'Transporte de Cargas'), ('Mudanças', 'CoteFrMudançasete'), ('Material Sem Nota', 'Material Sem Nota'), ('Moto', 'Moto'), ('Carga em Geral', 'Carga em Geral'), ('Máquina', 'Máquina'), ('Veículos', 'Veículos'), ('Não especificado', 'Não especificado')], default='Transporte de Cargas', max_length=100),
        ),
    ]
