# Generated by Django 3.2.25 on 2025-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0006_alter_cotacao_tipo_frete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='status_envio',
            field=models.CharField(choices=[('Duplicada', 'Duplicada'), ('Rejeitada', 'Rejeitada'), ('Falta Cubagem', 'Falta Cubagem'), ('Falta Preço', 'Falta Preço'), ('Enviado Whats + Email', 'Envio Whats + Email'), ('Enviado Whats', 'Enviado Whats'), ('Enviado Email', 'Enviado Email'), ('Envio Negado', 'Envio Negado'), ('Faltam Medidas', 'Faltam Medidas'), ('Não Enviado', 'Não Enviado'), ('Aguardando Coleta', 'Aguardando Coleta')], default='Falta Cubagem', max_length=50),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='tipo_frete',
            field=models.CharField(choices=[('Transporte de Cargas', 'Transporte de Cargas'), ('Mudanças', 'Mudanças'), ('Material Sem Nota', 'Material Sem Nota'), ('Moto', 'Moto'), ('Carga em Geral', 'Carga em Geral'), ('Máquina', 'Máquina'), ('Veículos', 'Veículos'), ('Não especificado', 'Não especificado')], default='Transporte de Cargas', max_length=100),
        ),
    ]
