# Generated by Django 3.2.25 on 2025-07-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0007_auto_20250731_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='status_envio',
            field=models.CharField(choices=[('Duplicada', 'Duplicada'), ('Rejeitada', 'Rejeitada'), ('Falta Cubagem', 'Falta Cubagem'), ('Falta Preço', 'Falta Preço'), ('Enviado Whats + Email', 'Envio Whats + Email'), ('Enviado Whats', 'Enviado Whats'), ('Enviado Email', 'Enviado Email'), ('Envio Negado', 'Envio Negado'), ('Faltam Medidas', 'Faltam Medidas'), ('Não Enviado', 'Não Enviado'), ('Aguardando Coleta', 'Aguardando Coleta'), ('Aguardando Pagamento', 'Aguardando Pagamento')], default='Falta Cubagem', max_length=50),
        ),
    ]
