# Generated by Django 3.2.25 on 2025-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0008_alter_cotacao_status_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='valor_mercadoria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='valor_proposta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
