# Generated by Django 3.2.25 on 2025-08-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0009_auto_20250801_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='cubagem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
