# Generated by Django 4.2.23 on 2025-08-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0010_alter_cotacao_cubagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='cubagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='rastreio',
            field=models.CharField(blank=True, choices=[('Cargas', 'Cargas'), ('CoteFrete', 'CoteFrete'), ('CoteTransporte', 'CoteTransporte'), ('Outros', 'Outros'), ('Email', 'Email'), ('Google', 'Google'), ('Guia', 'Guia'), ('Indicação', 'Indicação'), ('PortalDosFretes', 'PortalDosFretes'), ('Transvias', 'Transvias'), ('WhatsApp', 'WhatsApp'), ('Site', 'Site'), ('Telefone', 'Telefone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status_envio',
            field=models.CharField(choices=[('Duplicada', 'Duplicada'), ('Rejeitada', 'Rejeitada'), ('Falta Cubagem', 'Falta Cubagem'), ('Falta Preço', 'Falta Preço'), ('Enviado Whats + Email', 'Enviado Whats + Email'), ('Enviado Whats', 'Enviado Whats'), ('Enviado Email', 'Enviado Email'), ('Envio Negado', 'Envio Negado'), ('Faltam Medidas', 'Faltam Medidas'), ('Não Enviado', 'Não Enviado'), ('Aguardando Coleta', 'Aguardando Coleta'), ('Aguardando Pagamento', 'Aguardando Pagamento')], default='Não Enviado', max_length=50),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='valor_mercadoria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='valor_proposta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
