# Generated by Django 4.2.23 on 2025-08-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0011_alter_cotacao_cubagem_alter_cotacao_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='cubagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
