# Generated by Django 4.2.23 on 2025-08-24 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0012_alter_cotacao_cubagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='visivel',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se a cotação está ativa e visível para os usuários.', verbose_name='Visível'),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='data_recebimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
