# Generated by Django 4.2.23 on 2025-08-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0013_cotacao_visivel_alter_cotacao_data_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='status_cotacao',
            field=models.CharField(choices=[('Em Negociação', 'Em Negociação'), ('Aprovada', 'Aprovada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada'), ('Reprovada', 'Reprovada')], default='Em Negociação', max_length=50),
        ),
    ]
