# Generated by Django 4.2.23 on 2025-09-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0014_alter_cotacao_status_cotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, help_text='Data em que a cotação mudou para um status final (Finalizada, Aprovada, etc.).', null=True, verbose_name='Data de Finalização'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='data_ultima_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização da cotação.', verbose_name='Última Modificação'),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='data_recebimento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
