# Generated by Django 4.2.23 on 2025-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0015_cotacao_data_finalizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Post de Atualização',
                'verbose_name_plural': 'Posts de Atualizações',
                'ordering': ['-publication_date'],
            },
        ),
    ]
