# Generated by Django 4.2.23 on 2025-09-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0016_updatepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatepost',
            options={'ordering': ['-publication_date'], 'permissions': [('pode_gerenciar_updates', 'Pode gerenciar atualizações')], 'verbose_name': 'Post de Atualização', 'verbose_name_plural': 'Posts de Atualizações'},
        ),
    ]
