# Generated by Django 4.2.23 on 2025-10-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0017_alter_updatepost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('resposta', models.TextField(help_text='Você pode usar tags HTML básicas como <ul>, <li>, <strong>, etc.', verbose_name='Resposta')),
                ('categoria', models.CharField(choices=[('GERAL', 'Geral'), ('LISTA', 'Página Principal (Lista de Cotações)'), ('EDICAO', 'Página de Edição de Cotação')], default='GERAL', max_length=50, verbose_name='Categoria')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Itens com número menor aparecem primeiro.', verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente (FAQ)',
                'verbose_name_plural': 'Perguntas Frequentes (FAQ)',
                'ordering': ['categoria', 'ordem', 'pergunta'],
            },
        ),
    ]
