# Generated by Django 4.2.23 on 2025-10-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0018_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='rastreio',
            field=models.CharField(blank=True, choices=[('Cargas', 'Cargas'), ('CoteFrete', 'CoteFrete'), ('CoteTransporte', 'CoteTransporte'), ('Outros', 'Outros'), ('Email', 'Email'), ('Google', 'Google'), ('Guia', 'Guia'), ('GuiaMudanca', 'GuiaMudanca'), ('Indicação', 'Indicação'), ('PortalDosFretes', 'PortalDosFretes'), ('Transvias', 'Transvias'), ('WhatsApp', 'WhatsApp'), ('Site', 'Site'), ('Telefone', 'Telefone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
