# Generated by Django 4.2.23 on 2025-10-04 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quoteflow', '0019_alter_cotacao_rastreio_alter_cotacao_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='quoteflow.updatepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status de Leitura de Atualização',
                'verbose_name_plural': 'Status de Leitura de Atualizações',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
