# Generated by Django 4.2.23 on 2025-11-01 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0032_remove_perfil_megaapi_instance_key_and_more'),
        ('quoteflow', '0020_userupdatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_nfe', models.CharField(help_text='Chave de 44 dígitos da NF-e da mercadoria', max_length=44)),
                ('remetente_cnpj_cpf', models.CharField(max_length=18)),
                ('remetente_nome', models.CharField(max_length=255)),
                ('remetente_endereco', models.CharField(max_length=255)),
                ('destinatario_cnpj_cpf', models.CharField(max_length=18)),
                ('destinatario_nome', models.CharField(max_length=255)),
                ('cfop', models.CharField(max_length=4)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('id_api', models.CharField(blank=True, help_text='ID do documento na API de emissão', max_length=100, null=True)),
                ('chave_cte', models.CharField(blank=True, help_text='Chave do CTe após autorização', max_length=44, null=True)),
                ('xml_autorizado', models.FileField(blank=True, null=True, upload_to='documentos_fiscais/xml/')),
                ('pdf_documento', models.FileField(blank=True, null=True, upload_to='documentos_fiscais/pdf/')),
                ('cotacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='documento_fiscal', to='quoteflow.cotacao')),
            ],
        ),
        migrations.CreateModel(
            name='EmissaoMDFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista_nome', models.CharField(max_length=255)),
                ('motorista_cpf', models.CharField(max_length=14)),
                ('veiculo_placa', models.CharField(max_length=10)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('ctes_manifesto', models.ManyToManyField(related_name='manifestos', to='quoteflow.emissaodocumento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.empresa')),
            ],
        ),
    ]
