# Generated by Django 4.2.23 on 2025-11-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0034_remove_empresa_api_fiscal_token_and_more'),
        ('quoteflow', '0020_userupdatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_nfe', models.CharField(blank=True, help_text='Chave de 44 dígitos da NF-e da mercadoria', max_length=44, null=True)),
                ('remetente_cnpj_cpf', models.CharField(blank=True, max_length=18, null=True)),
                ('remetente_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('remetente_endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('destinatario_cnpj_cpf', models.CharField(blank=True, max_length=18, null=True)),
                ('destinatario_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cfop', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('id_api', models.CharField(blank=True, help_text='ID do documento na API de emissão', max_length=100, null=True)),
                ('chave_cte', models.CharField(blank=True, help_text='Chave do CTe após autorização', max_length=44, null=True)),
                ('xml_autorizado', models.FileField(blank=True, null=True, upload_to='documentos_fiscais/xml/')),
                ('pdf_documento', models.FileField(blank=True, null=True, upload_to='documentos_fiscais/pdf/')),
                ('cotacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='documento_fiscal', to='quoteflow.cotacao')),
            ],
        ),
        migrations.CreateModel(
            name='MensagemPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Modelo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_personalizadas', to='perfil.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmissaoMDFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('motorista_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('veiculo_placa', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, default='Pendente', max_length=50, null=True)),
                ('ctes_manifesto', models.ManyToManyField(blank=True, related_name='manifestos', to='quoteflow.emissaodocumento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.empresa')),
            ],
        ),
    ]
