# Generated by Django 4.2.23 on 2025-11-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0021_emissaodocumento_mensagempersonalizada_emissaomdfe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagempersonalizada',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Modelo de Mensagem', 'verbose_name_plural': 'Modelos de Mensagem'},
        ),
        migrations.AlterField(
            model_name='emissaodocumento',
            name='cotacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_fiscal', to='quoteflow.cotacao'),
        ),
    ]
