# Generated by Django 4.2.23 on 2025-11-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteflow', '0021_emissaodocumento_emissaomdfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaodocumento',
            name='destinatario_bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro do Destinatário'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='destinatario_cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP do Destinatário'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='destinatario_endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do Destinatário'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='destinatario_ie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual do Destinatário'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='destinatario_municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município do Destinatário'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='destinatario_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do Destinatário'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='remetente_bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro do Remetente'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='remetente_cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP do Remetente'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='remetente_ie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual do Remetente'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='remetente_municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município do Remetente'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='remetente_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do Remetente'),
        ),
        migrations.AddField(
            model_name='emissaodocumento',
            name='valor_total_servico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total do Serviço'),
        ),
        migrations.AlterField(
            model_name='emissaodocumento',
            name='cfop',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP'),
        ),
        migrations.AlterField(
            model_name='emissaodocumento',
            name='chave_nfe',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave da NF-e da Mercadoria'),
        ),
        migrations.AlterField(
            model_name='emissaodocumento',
            name='destinatario_cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF do Destinatário'),
        ),
        migrations.AlterField(
            model_name='emissaodocumento',
            name='destinatario_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome/Razão Social do Destinatário'),
        ),
        migrations.AlterField(
            model_name='emissaodocumento',
            name='remetente_cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF do Remetente'),
        ),
        migrations.AlterField(
            model_name='emissaodocumento',
            name='remetente_endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do Remetente'),
        ),
        migrations.AlterField(
            model_name='emissaodocumento',
            name='remetente_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome/Razão Social do Remetente'),
        ),
    ]
