# Generated by Django 4.2.23 on 2025-11-01 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0032_remove_perfil_megaapi_instance_key_and_more'),
        ('quoteflow', '0022_emissaodocumento_destinatario_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaomdfe',
            name='chave_mdfe',
            field=models.CharField(blank=True, help_text='Chave do MDFe após autorização', max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='emissaomdfe',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emissaomdfe',
            name='id_api',
            field=models.CharField(blank=True, help_text='ID do documento na API de emissão', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emissaomdfe',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AddField(
            model_name='emissaomdfe',
            name='pdf_documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos_fiscais/mdfe/pdf/'),
        ),
        migrations.AddField(
            model_name='emissaomdfe',
            name='uf_carregamento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de Carregamento'),
        ),
        migrations.AddField(
            model_name='emissaomdfe',
            name='uf_descarregamento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de Descarregamento'),
        ),
        migrations.AddField(
            model_name='emissaomdfe',
            name='xml_autorizado',
            field=models.FileField(blank=True, null=True, upload_to='documentos_fiscais/mdfe/xml/'),
        ),
        migrations.AlterField(
            model_name='emissaomdfe',
            name='ctes_manifesto',
            field=models.ManyToManyField(related_name='manifesto_associado', to='quoteflow.emissaodocumento', verbose_name="CTe's Incluídos"),
        ),
        migrations.AlterField(
            model_name='emissaomdfe',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestos_mdfe', to='perfil.empresa'),
        ),
        migrations.AlterField(
            model_name='emissaomdfe',
            name='motorista_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Motorista'),
        ),
        migrations.AlterField(
            model_name='emissaomdfe',
            name='motorista_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Motorista'),
        ),
        migrations.AlterField(
            model_name='emissaomdfe',
            name='veiculo_placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo'),
        ),
    ]
