"""
Django settings for loja project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
#from quoteflow.middleware import SubscriptionMiddleware, VersionSwitchMiddleware
from django.contrib.messages import constants
import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '34s66f2twc8c&q*i_@@4i(yp7wp0-d_hi3il7%1iom55xz(87w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '147.79.81.52',
    'mudancasja.com.br',
    'www.mudancasja.com.br',
    'preciflow.com.br',
    'www.preciflow.com.br',
    ]

# Application definition

INSTALLED_APPS = [
    'produto',
    'pedido',
    'perfil',
    'quoteflow',
    'enderecos',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_bootstrap4',
    'crispy_forms',
    'widget_tweaks',
    'django.contrib.humanize',
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # VOLTE A USAR A STRING ORIGINAL AQUI
    #'quoteflow.middleware.SubscriptionMiddleware',
    
    # 'perfil.middleware.admin_ip_restriction.AdminIPRestrictionMiddleware',
    # 'perfil.middleware.AdminIPRestrictionMiddleware',
    # 'quoteflow.middleware.VersionSwitchMiddleware',
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'loja.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'quoteflow.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'loja.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'staging_db',
        'USER': 'staging_user',
        'PASSWORD': 'Alejr3657###',
        'HOST': 'localhost',  # ou o IP do seu servidor de banco de dados
        'PORT': '5432',
    }
}
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


MESSAGE_TAGS = {
    constants.DEBUG: 'alert-info',
    constants.ERROR: 'alert-danger',
    constants.INFO: 'alert-info',
    constants.SUCCESS: 'alert-success',
    constants.WARNING: 'alert-warning',
}

# Sessão em dias: 60s * 60m * 24h * 1d
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7

# Salvar a cada requisição
SESSION_SAVE_EVERY_REQUEST = False

# Serializer - Padrão JSON
# SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
# Configurações de sessão
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True  # Forçar HTTPS
SECURE_HSTS_SECONDS = 31536000  # 1 ano
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'


TELEFONE_EMPRESA = '11 1234-5678'
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

# --- Configurações do Celery ---
# URL do seu message broker (Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
# Opcional: Backend para armazenar resultados de tarefas
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'


LOGIN_URL = 'perfil:login'
LOGIN_REDIRECT_URL = 'quoteflow:cotacao_list'


# --- CONFIGURAÇÕES ASAAS ---
# Comece com a URL e a Chave de API do SANDBOX
ASAAS_API_URL = 'https://sandbox.asaas.com/api/v3'
ASAAS_API_KEY = '$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmMxZTg1NTEyLTA3MWEtNGNhYy04MDViLWFhNGE5NTZlZjRhZTo6JGFhY2hfNGM5MDlhYmItNGQzMy00YTI1LWI5NmMtMjBjMDVlYzBkMjRi'

# Quando for para produção, troque para:
# ASAAS_API_URL = 'https://api.asaas.com/api/v3'
# ASAAS_API_KEY = 'SUA_CHAVE_DE_API_DE_PRODUCAO_AQUI'

# Chave para validar o webhook, invente uma senha segura.
ASAAS_WEBHOOK_TOKEN = 'Alejr3657###'

APP_BASE_URL = 'https://preciflow.com.br'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.hostinger.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#DEFAULT_FROM_EMAIL = 'contato@preciflow.com.br'
#EMAIL_CADASTRO = 'contato@preciflow.com.br'
#PASSWD_PRECIFLOW = '1B/qW?Bx^'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'suporte@portaldotransporte.com.br'
EMAIL_HOST_USER = 'suporte@portaldotransporte.com.br'
EMAIL_HOST_PASSWORD = 'Alejr3657###'
EMAIL_RECEIVER = 'suporte@portaldotransporte.com.br'
EMAIL_CADASTRO = 'suporte@portaldotransporte.com.br'
