# Generated by Django 4.2.23 on 2025-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEP',
            fields=[
                ('cep', models.CharField(help_text='CEP sem traços ou pontos', max_length=8, primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'CEP',
                'verbose_name_plural': 'CEPs',
            },
        ),
    ]
